social_auth_linkedin.settings:
  type: config_object
  label: 'Social Auth LinkedIn settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    scopes:
      type: string
      label: 'Scopes to be requested'
    endpoints:
      type: string
      label: 'API Endpoints to be requested'
