drd_agent.settings:
  type: config_object
  label: 'DRD Agent settings'
  mapping:
    debug_mode:
      type: boolean
      label: 'Whether the debug mode for this module is enabled or not'
    authorised:
      type: array
      label: 'List of authorised DRD instances'
    ott:
      type: array
      label: 'One time token'
