core.entity_view_display.*.*.*.third_party.layout_builder_restrictions:
  type: mapping
  label: 'Per-view-mode Layout Builder Restrictions settings'
  mapping:
    allowed_blocks:
      type: mapping
    allowed_layouts:
      type: mapping
